spring:
  profiles:
    active: dev

netty:
  ip: 127.0.0.1
  port: 7000

server:
  port: 8081
  #  error:
  #    path: /error
  #内嵌tomcat日志
  tomcat:
    accesslog:
      enabled: true
      directory: /Users/alioo/work/temp/tomcatLog/
      pattern: '%t %a %A %m %U%q %s %D %I %B'  #日志格式
      prefix: access
      suffix: .log



mac:
  letv: B8:FC:9A:3E:6A:DC,80:9F:9B:CA:7E:38


